# Copyright 2016 Mycroft AI, Inc.
#
# This file is part of Mycroft Core.
#
# Mycroft Core is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Mycroft Core is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Mycroft Core.  If not, see <http://www.gnu.org/licenses/>.


from adapt.intent import IntentBuilder
from mycroft.skills.core import MycroftSkill
import requests
import json

__author__ = 'jarbas'


class CryptocurrencySkill(MycroftSkill):
    def __init__(self):
        super(CryptocurrencySkill, self).__init__()
        self.currency = "eur"
        self.coins = {}
        self.get_coin_list()

    def initialize(self):
        for coin in self.coins.keys():
            flag = False
            for currency in ["eur", "rur", "ruble", "gbp", "pound", "usd",
                             "dollar", "u s d", "g b p", " r u r"]:
                if currency in coin:
                    self.register_vocabulary(coin, "TargetCurrency")
                    flag = True
            if not flag:
                self.register_vocabulary(coin, "CryptoCurrency")

        intent = IntentBuilder("CryptocoinPriceIntent").require(
            "PriceKeyword").optionally(
            "TargetCurrency").require("CryptoCurrency").build()
        self.register_intent(intent, self.handle_coin_price)

        intent = IntentBuilder("CryptocoinChangeIntent").require(
            "ChangeKeyword").optionally(
            "TargetCurrency").require("CryptoCurrency").build()
        self.register_intent(intent, self.handle_coin_change)

        intent = IntentBuilder("CryptocoinVolumeIntent").require(
            "VolumeKeyword").optionally(
            "TargetCurrency").require("CryptoCurrency").build()
        self.register_intent(intent, self.handle_coin_volume)

    def handle_coin_price(self, message):
        # TODO find other mechanism
        # hack to correctly trigger intent f you say "bitcoin price change"
        utterance = message.data["utterance"]
        if "change" in utterance or "move" in utterance or "increase" in \
                utterance or "decrease" in utterance:
            self.handle_coin_change(message)
            return
        if "volume" in utterance:
            self.handle_coin_volume(message)
            return
        coin = message.data.get("CryptoCurrency").lower()
        currency = message.data.get("TargetCurrency", self.currency)
        code = self.coins[coin]
        if not code:
            self.speak_dialog("bad_coin")
            return
        currency_code = self.coin_code(currency)
        if not currency_code:
            self.speak_dialog("bad_coin", {"coin": currency_code})
            return
        url = "https://api.cryptonator.com/api/ticker/" + code + "-" + currency_code
        r = requests.get(url)
        j = json.loads(r.text)
        data = j["ticker"]
        success = j["success"]
        if not success:
            error = j["error"]
            self.speak_dialog("cryptonator.error", {"error": error})
            return
        price = data["price"]
        base = data["base"]
        target = data["target"]
        self.speak_dialog("cryptonator.price", {"base": coin, "target":
            currency, "price": price})
        self.set_context("CryptoCurrency", base)
        self.set_context("TargetCurrency", target)

    def handle_coin_change(self, message):
        coin = message.data.get("CryptoCurrency").lower()
        currency = message.data.get("TargetCurrency", self.currency)
        code = self.coins[coin]
        if not code:
            self.speak_dialog("bad_coin", {"coin": coin})
            return
        currency_code = self.coin_code(currency)
        if not currency_code:
            self.speak_dialog("bad_coin", {"coin": currency_code})
            return
        url = "https://api.cryptonator.com/api/ticker/" + code + "-" + currency_code
        r = requests.get(url)
        j = json.loads(r.text)
        data = j["ticker"]
        success = j["success"]
        if not success:
            error = j["error"]
            self.speak_dialog("cryptonator.error", {"error": error})
            return
        base = data["base"]
        target = data["target"]
        past_hour_change = data["change"]
        self.speak_dialog("cryptonator.change", {"base": coin, "target":
            currency, "change": past_hour_change})
        self.set_context("CryptoCurrency", base)
        self.set_context("TargetCurrency", target)

    def handle_coin_volume(self, message):
        coin = message.data.get("CryptoCurrency").lower()
        currency = message.data.get("TargetCurrency", self.currency)
        code = self.coins[coin]
        if not code:
            self.speak_dialog("bad_coin", {"coin": coin})
            return
        currency_code = self.coin_code(currency)
        if not currency_code:
            self.speak_dialog("bad_coin", {"coin": currency_code})
            return
        url = "https://api.cryptonator.com/api/ticker/" + code + "-" + currency_code
        r = requests.get(url)
        j = json.loads(r.text)
        data = j["ticker"]
        success = j["success"]
        if not success:
            error = j["error"]
            self.speak_dialog("cryptonator.error", {"error": error})
            return
        volume = data["volume"]
        base = data["base"]
        target = data["target"]
        self.speak_dialog("cryptonator.volume", {"base": coin, "target":
            currency, "volume": volume})
        self.set_context("CryptoCurrency", base)
        self.set_context("TargetCurrency", target)

    def coin_code(self, string):
        # TODO all the supported fiat coins
        string = string.lower()
        if string in ["eur", "euro", "euros"]:
            return "EUR"
        if string in ["rur", "ruble", "rubles"]:
            return "RUR"
        if string in ["gbp", "pound", "pounds", "british pound", "british "
                                                                 "pounds",
                      "british pound sterling"]:
            return "GBP"
        if string in ["usd", "american dollars", "american dollar",
                      "dollar", "dollars", "us dollar", "us dollars",
                      "u s dollar", "u s dollars", "u s d", "$"]:
            return "USD"
        if string in self.coins.keys():
            return self.coins[string]
        return None

    def get_coin_list(self):
        # copy pasta of supported cryptonator coins
        # TODO use api not copy pasta, it wasnt behaving at time of coding
        coin_list = {
            '007': '007',
            '1337': '1337',
            '1ST': '1ST',
            '2015': '2015',
            '2GIVE': '2GIVE',
            '32BIT': '32BIT',
            '365': '365',
            '404': '404',
            '611': '611',
            '8BT': '8BT',
            '9COIN': '9COIN',
            'ABC': 'ABC',
            'ABN': 'ABN',
            'ACES': 'ACES',
            'ACN': 'ACN',
            'ACOIN': 'ACOIN',
            'ACP': 'ACP',
            'ADA': 'ADA',
            'ADAM': 'ADAM',
            'ADC': 'ADC',
            'ADL': 'ADL',
            'ADT': 'ADT',
            'ADX': 'ADX',
            'Adzcoin': 'ADZ',
            'AEB': 'AEB',
            'AEO': 'AEO',
            'Aeon': 'AEON',
            'Agoras Tokens': 'AGRS',
            'AGRI': 'AGRI',
            'AIB': 'AIB',
            'AIR': 'AIR',
            'AL': 'AL',
            'ALC': 'ALC',
            'ALIEN': 'ALIEN',
            'ALL': 'ALL',
            'ALT': 'ALT',
            'ALTC': 'ALTC',
            'AM': 'AM',
            'AMB': 'AMB',
            'AMBER': 'AMBER',
            'AMS': 'AMS',
            'ANI': 'ANI',
            'AntiBitcoin': 'ANTI',
            'Applecoin': 'APC',
            'APW': 'APW',
            'APX': 'APX',
            'Aragon': 'ANT',
            'ARB': 'ARB',
            'ARC': 'ARC',
            'ARCX': 'ARCX',
            'ARD': 'ARD',
            'ARDR': 'ARDR',
            'ARE': 'ARE',
            'ARK': 'ARK',
            'ARM': 'ARM',
            'ARTA': 'ARTA',
            'ArtByte': 'ABY',
            'ARTC': 'ARTC',
            'ASAFE': 'ASAFE',
            'Asiadigicoin': 'ADCN',
            'AST': 'AST',
            'ATB': 'ATB',
            'ATM': 'ATM',
            'ATOM': 'ATOM',
            'ATU': 'ATU',
            'ATX': 'ATX',
            'Augur': 'REP',
            'AUM': 'AUM',
            'Auroracoin': 'AUR',
            'AURS': 'AURS',
            'AUS': 'AUS',
            'Australian Dollar': 'AUD',
            'AV': 'AV',
            'AVT': 'AVT',
            'AXIOM': 'AXIOM',
            'B2': 'B2',
            'B3': 'B3',
            'BAB': 'BAB',
            'BAN': 'BAN',
            'BAS': 'BAS',
            'BASH': 'BASH',
            'BAT': 'BAT',
            'Bata': 'BTA',
            'BATL': 'BATL',
            'BAY': 'BAY',
            'BBH': 'BBH',
            'BBP': 'BBP',
            'BCM': 'BCM',
            'BCU': 'BCU',
            'BDC': 'BDC',
            'BDL': 'BDL',
            'BEE': 'BEE',
            'BEEP': 'BEEP',
            'BEEZ': 'BEEZ',
            'BellaCoin': 'BELA',
            'BENJI': 'BENJI',
            'BERNcash': 'BERN',
            'BEST': 'BEST',
            'BET': 'BET',
            'BHC': 'BHC',
            'BigUp': 'BIGUP',
            'BILL': 'BILL',
            'BiosCrypto': 'BIOS',
            'BIT': 'BIT',
            'BIT16': 'BIT16',
            'BitBean': 'BITB',
            'BITCF': 'BITCF',
            'Bitcoin': 'BTC',
            'Bitcoin Cash': 'BCH',
            'Bitcoin Plus': 'XBC',
            'BitcoinDark': 'BTCD',
            'Bitcrystals': 'BCY',
            'Bitmark': 'BTM',
            'BITOK': 'BITOK',
            'BITON': 'BITON',
            'Bitpark coin': 'BPC',
            'BitQuark': 'BTQ',
            'BitSend': 'BSD',
            'BitShares': 'BTS',
            'BitShares PTS': 'PTS',
            'BitSwift': 'SWIFT',
            'BIZ': 'BIZ',
            'Blackcoin': 'BLK',
            'BlackJack': 'JACK',
            'Blakecoin': 'BLC',
            'BLAZR': 'BLAZR',
            'Blitzcoin': 'BLITZ',
            'Blocknet': 'BLOCK',
            'BLU': 'BLU',
            'BLUS': 'BLUS',
            'BMC': 'BMC',
            'BNT': 'BNT',
            'BOD': 'BOD',
            'Bolivarcoin': 'BOLI',
            'BOMB': 'BOMB',
            'BON': 'BON',
            'BoostCoin': 'BOST',
            'BOS': 'BOS',
            'BOSS': 'BOSS',
            'BOT': 'BOT',
            'BPOK': 'BPOK',
            'BQ': 'BQ',
            'BQX': 'BQX',
            'BRDD': 'BRDD',
            'BRE': 'BRE',
            'BRIT': 'BRIT',
            'British Pound Sterling': 'GBP',
            'BRK': 'BRK',
            'BRONZ': 'BRONZ',
            'BRX': 'BRX',
            'BS': 'BS',
            'BSC': 'BSC',
            'BSDB': 'BSDB',
            'BSH': 'BSH',
            'BST': 'BST',
            'BSTK': 'BSTK',
            'BT1': 'BT1',
            'BT2': 'BT2',
            'BTCHC': 'BTCHC',
            'BTCO': 'BTCO',
            'BTCS': 'BTCS',
            'BTCU': 'BTCU',
            'BTD': 'BTD',
            'BTP': 'BTP',
            'BTTF': 'BTTF',
            'BTXC': 'BTXC',
            'BTZ': 'BTZ',
            'BUB': 'BUB',
            'BUCKS': 'BUCKS',
            'Burst': 'BURST',
            'BUS': 'BUS',
            'BUZZ': 'BUZZ',
            'BVC': 'BVC',
            'BXT': 'BXT',
            'Byteball': 'GBYTE',
            'Bytecent': 'BYC',
            'Bytecoin': 'BCN',
            'C0C0': 'C0C0',
            'Cabbage Unit': 'CAB',
            'CAID': 'CAID',
            'CALC': 'CALC',
            'Canadian Dollar': 'CAD',
            'CannabisCoin': 'CANN',
            'Capricoin': 'CPC',
            'CAPT': 'CAPT',
            'CAT': 'CAT',
            'CB': 'CB',
            'CBD': 'CBD',
            'CCB': 'CCB',
            'CCC': 'CCC',
            'CCRB': 'CCRB',
            'CCT': 'CCT',
            'CCX': 'CCX',
            'CD': 'CD',
            'CDN': 'CDN',
            'CDT': 'CDT',
            'CF': 'CF',
            'CFC': 'CFC',
            'CFI': 'CFI',
            'CH': 'CH',
            'CHEMX': 'CHEMX',
            'CHESS': 'CHESS',
            'CHILL': 'CHILL',
            'Chinese Yuan': 'CNY',
            'ChipCoin': 'CHIP',
            'CHOOF': 'CHOOF',
            'CIN': 'CIN',
            'CIRC': 'CIRC',
            'CJ': 'CJ',
            'CJC': 'CJC',
            'CKS': 'CKS',
            'Clams': 'CLAM',
            'CLICK': 'CLICK',
            'CLINT': 'CLINT',
            'Cloakcoin': 'CLOAK',
            'CLR': 'CLR',
            'CLUB': 'CLUB',
            'CLUD': 'CLUD',
            'CME': 'CME',
            'CMT': 'CMT',
            'CNB': 'CNB',
            'CNC': 'CNC',
            'CND': 'CND',
            'CNNC': 'CNNC',
            'CNT': 'CNT',
            'CNX': 'CNX',
            'COC': 'COC',
            'COIN': 'COIN',
            'Coin2.1': 'C2',
            'Colossuscoin2.0': 'CV2',
            'CON': 'CON',
            'CONX': 'CONX',
            'CORG': 'CORG',
            'COS': 'COS',
            'Counterparty': 'XCP',
            'COV': 'COV',
            'COVAL': 'COVAL',
            'COX': 'COX',
            'CRAB': 'CRAB',
            'CRAFT': 'CRAFT',
            'CRC': 'CRC',
            'CRE': 'CRE',
            'Creditbit': 'CRB',
            'CrevaCoin': 'CREVA',
            'CRM': 'CRM',
            'CRNK': 'CRNK',
            'CROC': 'CROC',
            'CRPC': 'CRPC',
            'CRS': 'CRS',
            'CRT': 'CRT',
            'CRW': 'CRW',
            'CRX': 'CRX',
            'CRY': 'CRY',
            'CryptoEscudo': 'CESC',
            'Cryptonite': 'XCN',
            'CSMIC': 'CSMIC',
            'CSN': 'CSN',
            'CTIC': 'CTIC',
            'CTIC2': 'CTIC2',
            'CTK': 'CTK',
            'CTL': 'CTL',
            'CTO': 'CTO',
            'CTR': 'CTR',
            'Curecoin': 'CURE',
            'CVC': 'CVC',
            'DANC': 'DANC',
            'DAR': 'DAR',
            'DarkGoldCoin': 'DGD',
            'DAS': 'DAS',
            'Dash': 'DASH',
            'Dashcoin': 'DSH',
            'DASHS': 'DASHS',
            'DBG': 'DBG',
            'DBIX': 'DBIX',
            'DBLK': 'DBLK',
            'DBT': 'DBT',
            'DBTC': 'DBTC',
            'DC': 'DC',
            'DCC': 'DCC',
            'DCK': 'DCK',
            'DCN': 'DCN',
            'DCRE': 'DCRE',
            'DCT': 'DCT',
            'DCYP': 'DCYP',
            'DDC': 'DDC',
            'DDF': 'DDF',
            'DEA': 'DEA',
            'DECR': 'DECR',
            'Decred': 'DCR',
            'DEEP': 'DEEP',
            'DEN': 'DEN',
            'DESH': 'DESH',
            'Destiny': 'DES',
            'DETH': 'DETH',
            'DEUS': 'DEUS',
            'Deutsche eMark': 'DEM',
            'DFT': 'DFT',
            'DGCS': 'DGCS',
            'DGMS': 'DGMS',
            'DGORE': 'DGORE',
            'Diamond': 'DMD',
            'DIBC': 'DIBC',
            'DIC': 'DIC',
            'Digibyte': 'DGB',
            'DigiCube': 'CUBE',
            'Digitalcoin': 'DGC',
            'DigitalNote': 'XDN',
            'Dimecoin': 'DIME',
            'DIRT': 'DIRT',
            'DKC': 'DKC',
            'DLC': 'DLC',
            'DLISK': 'DLISK',
            'DLT': 'DLT',
            'DMC': 'DMC',
            'DNotes': 'NOTE',
            'DNT': 'DNT',
            'Dogecoin': 'DOGE',
            'DopeCoin': 'DOPE',
            'DOTA': 'DOTA',
            'DP2': 'DP2',
            'DPAY': 'DPAY',
            'DPC': 'DPC',
            'DPY': 'DPY',
            'DRACO': 'DRACO',
            'DRM': 'DRM',
            'DRM8': 'DRM8',
            'DROP': 'DROP',
            'DRZ': 'DRZ',
            'DTB': 'DTB',
            'DTT': 'DTT',
            'DUB': 'DUB',
            'DubaiCoin': 'DBIC',
            'DUO': 'DUO',
            'DUR': 'DUR',
            'DUS': 'DUS',
            'DUST': 'DUST',
            'DUX': 'DUX',
            'DXO': 'DXO',
            'DYN': 'DYN',
            'EA': 'EA',
            'EBE': 'EBE',
            'EBH': 'EBH',
            'EBST': 'EBST',
            'EBT': 'EBT',
            'EC': 'EC',
            'ECA': 'ECA',
            'ECCHI': 'ECCHI',
            'ECLI': 'ECLI',
            'ECN': 'ECN',
            'ECO': 'ECO',
            'ECOB': 'ECOB',
            'EDG': 'EDG',
            'EDIT': 'EDIT',
            'EDR2': 'EDR2',
            'EDRC': 'EDRC',
            'EDRCoin': 'EDR',
            'EET': 'EET',
            'EETT': 'EETT',
            'EGG': 'EGG',
            'EGO': 'EGO',
            'Einsteinium': 'EMC2',
            'EKO': 'EKO',
            'EL': 'EL',
            'ELcoin': 'ELCO',
            'ELE': 'ELE',
            'Electronic Gulden': 'EFL',
            'ELI': 'ELI',
            'ELM': 'ELM',
            'EMB': 'EMB',
            'EME': 'EME',
            'Emercoin': 'EMC',
            'EMG': 'EMG',
            'EMP': 'EMP',
            'EMPC': 'EMPC',
            'Energycoin': 'ENRG',
            'ENT': 'ENT',
            'ENTER': 'ENTER',
            'EOS': 'EOS',
            'EPC': 'EPC',
            'EPY': 'EPY',
            'EQM': 'EQM',
            'EQT': 'EQT',
            'EQUAL': 'EQUAL',
            'ERC': 'ERC',
            'ESB': 'ESB',
            'ESC': 'ESC',
            'ESP': 'ESP',
            'ETB': 'ETB',
            'ETCO': 'ETCO',
            'Ethereum': 'ETH',
            'Ethereum Classic': 'ETC',
            'ETHS': 'ETHS',
            'ETP': 'ETP',
            'ETT': 'ETT',
            'ETX': 'ETX',
            'EUC': 'EUC',
            'EURC': 'EURC',
            'Euro': 'EUR',
            'EVA': 'EVA',
            'EverGreenCoin': 'EGC',
            'EVIL': 'EVIL',
            'EVO': 'EVO',
            'EVR': 'EVR',
            'EVX': 'EVX',
            'EXCL': 'EXCL',
            'EXIT': 'EXIT',
            'Expanse': 'EXP',
            'Factom': 'FCT',
            'FADE': 'FADE',
            'Faircoin': 'FAIR',
            'FAZZ': 'FAZZ',
            'FCASH': 'FCASH',
            'FCH': 'FCH',
            'FCN': 'FCN',
            'Feathercoin': 'FTC',
            'Fedoracoin': 'TIPS',
            'FFC': 'FFC',
            'FIDEL': 'FIDEL',
            'FIND': 'FIND',
            'FJC': 'FJC',
            'Florincoin': 'FLO',
            'FLVR': 'FLVR',
            'FLX': 'FLX',
            'Flycoin': 'FLY',
            'FNC': 'FNC',
            'FoldingCoin': 'FLDC',
            'FOREX': 'FOREX',
            'Franko': 'FRK',
            'FRDC': 'FRDC',
            'FRE': 'FRE',
            'FRN': 'FRN',
            'FRST': 'FRST',
            'FRWC': 'FRWC',
            'FSN': 'FSN',
            'FST': 'FST',
            'FU': 'FU',
            'FUE': 'FUE',
            'FUN': 'FUN',
            'FUNC': 'FUNC',
            'FUNK': 'FUNK',
            'FUTC': 'FUTC',
            'FUZZ': 'FUZZ',
            'FX': 'FX',
            'FYN': 'FYN',
            'FYP': 'FYP',
            'GAC': 'GAC',
            'GAIN': 'GAIN',
            'GAKH': 'GAKH',
            'GAM': 'GAM',
            'GameBet Coin': 'GBT',
            'GameCredits': 'GAME',
            'GARY': 'GARY',
            'GAS': 'GAS',
            'GB': 'GB',
            'GBC': 'GBC',
            'GBG': 'GBG',
            'GBIT': 'GBIT',
            'GBRC': 'GBRC',
            'GCC': 'GCC',
            'GCC24': 'GCC24',
            'GD2': 'GD2',
            'GE': 'GE',
            'GELUK': 'GELUK',
            'Genstake': 'GEN',
            'GeoCoin': 'GEO',
            'GER': 'GER',
            'GHS': 'GHS',
            'GIFT': 'GIFT',
            'GIG': 'GIG',
            'GIZ': 'GIZ',
            'GLC': 'GLC',
            'GLO': 'GLO',
            'GlobalBoost-Y': 'BSTY',
            'GLTC': 'GLTC',
            'GML': 'GML',
            'GMX': 'GMX',
            'GNO': 'GNO',
            'GOAT': 'GOAT',
            'GoCoineR': 'GCR',
            'GoldCoin': 'GLD',
            'Golem': 'GNT',
            'GOLOS': 'GOLOS',
            'GOON': 'GOON',
            'GOTX': 'GOTX',
            'GP': 'GP',
            'GPU': 'GPU',
            'GRAM': 'GRAM',
            'GRAV': 'GRAV',
            'Gridcoin': 'GRC',
            'Groestlcoin': 'GRS',
            'GRP': 'GRP',
            'GRWI': 'GRWI',
            'GSB': 'GSB',
            'GSR': 'GSR',
            'GSX': 'GSX',
            'GSY': 'GSY',
            'GT': 'GT',
            'GTFO': 'GTFO',
            'GUC': 'GUC',
            'Gulden': 'NLG',
            'GUM': 'GUM',
            'GUP': 'GUP',
            'GYC': 'GYC',
            'HAC': 'HAC',
            'HALLO': 'HALLO',
            'HAWK': 'HAWK',
            'HBT': 'HBT',
            'HCC': 'HCC',
            'HEAT': 'HEAT',
            'HEEL': 'HEEL',
            'Hempcoin': 'THC',
            'HempCoin': 'HMP',
            'HET': 'HET',
            'HiCoin': 'XHI',
            'HIFUN': 'HIFUN',
            'HIRE': 'HIRE',
            'HKG': 'HKG',
            'HMQ': 'HMQ',
            'HNC': 'HNC',
            'HOdlcoin': 'HODL',
            'HOP': 'HOP',
            'HOPE': 'HOPE',
            'HPC': 'HPC',
            'HRB': 'HRB',
            'HSP': 'HSP',
            'HSR': 'HSR',
            'HTC': 'HTC',
            'HTMLCOIN': 'HTML5',
            'HUC': 'HUC',
            'HUS': 'HUS',
            'HVCO': 'HVCO',
            'HVN': 'HVN',
            'HZT': 'HZT',
            'IBANK': 'IBANK',
            'IBITS': 'IBITS',
            'IBT': 'IBT',
            'iCash': 'ICASH',
            'ICO': 'ICO',
            'ICOBI': 'ICOBI',
            'Iconomi': 'ICN',
            'ICX': 'ICX',
            'IET': 'IET',
            'IFLT': 'IFLT',
            'IFT': 'IFT',
            'IGN': 'IGN',
            'ILC': 'ILC',
            'IML': 'IML',
            'IMPS': 'IMPS',
            'INC': 'INC',
            'INCNT': 'INCNT',
            'INCP': 'INCP',
            'IND': 'IND',
            'Indonesian Rupiah': 'IDR',
            'INF': 'INF',
            'Infinitecoin': 'IFC',
            'Influxcoin': 'INFX',
            'INGT': 'INGT',
            'INPAY': 'INPAY',
            'INSN': 'INSN',
            'INV': 'INV',
            'IO Coin': 'IOC',
            'ION': 'ION',
            'IONX': 'IONX',
            'IOP': 'IOP',
            'IOT': 'IOT',
            'ISE': 'ISE',
            'ITI': 'ITI',
            'IUS': 'IUS',
            'IVZ': 'IVZ',
            'IXT': 'IXT',
            'Japanese Yen': 'JPY',
            'JIF': 'JIF',
            'JIO': 'JIO',
            'JNS': 'JNS',
            'JOBS': 'JOBS',
            'JPC': 'JPC',
            'JW': 'JW',
            'JWL': 'JWL',
            'Karma': 'KARMA',
            'KARMC': 'KARMC',
            'KAT': 'KAT',
            'KC': 'KC',
            'KGB': 'KGB',
            'KGC': 'KGC',
            'KGDC': 'KGDC',
            'KIDS': 'KIDS',
            'KLC': 'KLC',
            'KMD': 'KMD',
            'KOBO': 'KOBO',
            'KoreCoin': 'KORE',
            'KPL': 'KPL',
            'KRAK': 'KRAK',
            'KRB': 'KRB',
            'KRONE': 'KRONE',
            'KRS': 'KRS',
            'Krypton': 'KR',
            'KUBO': 'KUBO',
            'KUSH': 'KUSH',
            'L7S': 'L7S',
            'LANA': 'LANA',
            'LAT': 'LAT',
            'LAZ': 'LAZ',
            'LBC': 'LBC',
            'LBT': 'LBT',
            'LC': 'LC',
            'LDC': 'LDC',
            'LDCN': 'LDCN',
            'LeaCoin': 'LEA',
            'LEAF': 'LEAF',
            'LEO': 'LEO',
            'LET': 'LET',
            'LGBTQ': 'LGBTQ',
            'LGD': 'LGD',
            'LIMX': 'LIMX',
            'LINDA': 'LINDA',
            'LIR': 'LIR',
            'Lisk': 'LSK',
            'LITE': 'LITE',
            'Litecoin': 'LTC',
            'Litecred': 'LTCR',
            'LiteDoge': 'LDOGE',
            'LIV': 'LIV',
            'LKC': 'LKC',
            'LMC': 'LMC',
            'LOC': 'LOC',
            'LOYAL': 'LOYAL',
            'LRC': 'LRC',
            'LSB': 'LSB',
            'LSD': 'LSD',
            'LTCU': 'LTCU',
            'LTD': 'LTD',
            'LTH': 'LTH',
            'LTS': 'LTS',
            'LUCKY': 'LUCKY',
            'LUNA': 'LUNA',
            'LUNYR': 'LUNYR',
            'Lunyr': 'LUN',
            'LUS': 'LUS',
            'LUX': 'LUX',
            'M1': 'M1',
            'MAD': 'MAD',
            'Magi': 'XMG',
            'MAI': 'MAI',
            'MaidSafeCoin': 'MAID',
            'MALC': 'MALC',
            'MAN': 'MAN',
            'MAPC': 'MAPC',
            'MarteXcoin': 'MXT',
            'MARV': 'MARV',
            'Mastercoin (Omni)': 'OMNI',
            'MAY': 'MAY',
            'MAZE': 'MAZE',
            'MBL': 'MBL',
            'MCA': 'MCA',
            'MCAP': 'MCAP',
            'MCAR': 'MCAR',
            'MCO': 'MCO',
            'MCR': 'MCR',
            'Memetic': 'MEME',
            'MEN': 'MEN',
            'MET': 'MET',
            'MG': 'MG',
            'MGC': 'MGC',
            'MGO': 'MGO',
            'MHC': 'MHC',
            'MindCoin': 'MND',
            'MIP': 'MIP',
            'MIX': 'MIX',
            'MLN': 'MLN',
            'MM': 'MM',
            'MMXVI': 'MMXVI',
            'MNE': 'MNE',
            'MNM': 'MNM',
            'MOIN': 'MOIN',
            'MojoCoin': 'MOJO',
            'MonaCoin': 'MONA',
            'Monero': 'XMR',
            'MonetaryUnit': 'MUE',
            'Mooncoin': 'MOON',
            'MOOND': 'MOOND',
            'MOTO': 'MOTO',
            'MPK': 'MPK',
            'MPRO': 'MPRO',
            'MRB': 'MRB',
            'MRP': 'MRP',
            'MRV': 'MRV',
            'MSCN': 'MSCN',
            'MSP': 'MSP',
            'MST': 'MST',
            'MTH': 'MTH',
            'MTL': 'MTL',
            'MUSIC': 'MUSIC',
            'MUU': 'MUU',
            'MVR': 'MVR',
            'MYB': 'MYB',
            'MYST': 'MYST',
            'N2O': 'N2O',
            'N7': 'N7',
            'Namecoin': 'NMC',
            'NAMO': 'NAMO',
            'NANOX': 'NANOX',
            'NAT': 'NAT',
            'Nautiluscoin': 'NAUT',
            'NAV Coin': 'NAV',
            'NBIT': 'NBIT',
            'NCS': 'NCS',
            'NDC': 'NDC',
            'NEBU': 'NEBU',
            'NEM': 'XEM',
            'NEO': 'NEO',
            'NeosCoin': 'NEOS',
            'NETC': 'NETC',
            'NetCoin': 'NET',
            'NETKO': 'NETKO',
            'Neutron': 'NTRN',
            'NevaCoin': 'NEVA',
            'NEWB': 'NEWB',
            'Nexus': 'NXS',
            'NIC': 'NIC',
            'NICE': 'NICE',
            'NKA': 'NKA',
            'NKC': 'NKC',
            'NKT': 'NKT',
            'NLC2': 'NLC2',
            'NMR': 'NMR',
            'NO': 'NO',
            'NODES': 'NODES',
            'NOO': 'NOO',
            'Novacoin': 'NVC',
            'NPC': 'NPC',
            'NRC': 'NRC',
            'NTM': 'NTM',
            'NTO': 'NTO',
            'NUBIS': 'NUBIS',
            'NuBits': 'NBT',
            'NUKE': 'NUKE',
            'NUM': 'NUM',
            'NXC': 'NXC',
            'NXT': 'NXT',
            'NZC': 'NZC',
            'OAX': 'OAX',
            'OBITS': 'OBITS',
            'OBS': 'OBS',
            'OBT': 'OBT',
            'OCOW': 'OCOW',
            'OD': 'OD',
            'ODNT': 'ODNT',
            'OKCash': 'OK',
            'OLIT': 'OLIT',
            'OLYMP': 'OLYMP',
            'OMC': 'OMC',
            'OMG': 'OMG',
            'OP': 'OP',
            'OPAL': 'OPAL',
            'OPNC': 'OPNC',
            'OPT': 'OPT',
            'ORM': 'ORM',
            'ORME': 'ORME',
            'OS': 'OS',
            'OS76': 'OS76',
            'OTC': 'OTC',
            'OTX': 'OTX',
            'OUS': 'OUS',
            'OWB': 'OWB',
            'OZC': 'OZC',
            'P7C': 'P7C',
            'PAC': 'PAC',
            'PAK': 'PAK',
            'PAL': 'PAL',
            'Pandacoin': 'PND',
            'PARA': 'PARA',
            'PART': 'PART',
            'PARTY': 'PARTY',
            'PASC': 'PASC',
            'PAY': 'PAY',
            'Paycoin': 'XPY',
            'PAYP': 'PAYP',
            'PBK': 'PBK',
            'PBT': 'PBT',
            'PCS': 'PCS',
            'PDC': 'PDC',
            'Peercoin': 'PPC',
            'PEO': 'PEO',
            'PGUC': 'PGUC',
            'PHR': 'PHR',
            'PHX': 'PHX',
            'PIEX': 'PIEX',
            'PIN': 'PIN',
            'PING': 'PING',
            'Pinkcoin': 'PC',
            'PINKX': 'PINKX',
            'PIO': 'PIO',
            'PIPL': 'PIPL',
            'PIVX': 'PIVX',
            'PIX': 'PIX',
            'PIZZA': 'PIZZA',
            'PKB': 'PKB',
            'PLAY': 'PLAY',
            'PLB': 'PLB',
            'PLBT': 'PLBT',
            'PLN': 'PLN',
            'PLNC': 'PLNC',
            'PLR': 'PLR',
            'PLU': 'PLU',
            'PNC': 'PNC',
            'PNK': 'PNK',
            'POE': 'POE',
            'POKE': 'POKE',
            'POLY': 'POLY',
            'POM': 'POM',
            'PONZ2': 'PONZ2',
            'PONZI': 'PONZI',
            'POPPY': 'POPPY',
            'PosEx': 'PEX',
            'POST': 'POST',
            'POSW': 'POSW',
            'Potcoin': 'POT',
            'POWER': 'POWER',
            'PPT': 'PPT',
            'PPY': 'PPY',
            'PQT': 'PQT',
            'PRC': 'PRC',
            'PRES': 'PRES',
            'PRG': 'PRG',
            'Prime-XI': 'PXI',
            'Primecoin': 'XPM',
            'PRIMU': 'PRIMU',
            'PRM': 'PRM',
            'PRO': 'PRO',
            'PROC': 'PROC',
            'PSB': 'PSB',
            'PSI': 'PSI',
            'PST': 'PST',
            'PTA': 'PTA',
            'PTC': 'PTC',
            'PTO': 'PTO',
            'PTOY': 'PTOY',
            'PUPA': 'PUPA',
            'PURE': 'PURE',
            'PUT': 'PUT',
            'PUTIN': 'PUTIN',
            'PWR': 'PWR',
            'PX': 'PX',
            'QAU': 'QAU',
            'QBC': 'QBC',
            'QCN': 'QCN',
            'QRL': 'QRL',
            'QTU': 'QTU',
            'QTUM': 'QTUM',
            'QTZ': 'QTZ',
            'QWARK': 'QWARK',
            'RAD': 'RAD',
            'RADI': 'RADI',
            'Radium': 'RADS',
            'RAI': 'RAI',
            'RateCoin': 'XRA',
            'RATIO': 'RATIO',
            'RBIT': 'RBIT',
            'RCN': 'RCN',
            'Reddcoin': 'RDD',
            'REE': 'REE',
            'RET': 'RET',
            'Revenu': 'REV',
            'RGC': 'RGC',
            'RHFC': 'RHFC',
            'RICE': 'RICE',
            'RICHX': 'RICHX',
            'RID': 'RID',
            'Riecoin': 'RIC',
            'Rimbit': 'RBT',
            'RING': 'RING',
            'RIO': 'RIO',
            'Ripple': 'XRP',
            'RISE': 'RISE',
            'RIYA': 'RIYA',
            'RKC': 'RKC',
            'RLC': 'RLC',
            'RLT': 'RLT',
            'RMS': 'RMS',
            'RNC': 'RNC',
            'ROBO': 'ROBO',
            'ROLC': 'ROLC',
            'RONIN': 'RONIN',
            'ROO': 'ROO',
            'RosCoin': 'ROS',
            'ROYAL': 'ROYAL',
            'RPC': 'RPC',
            'RRT': 'RRT',
            'RSGP': 'RSGP',
            'Rubies': 'RBIES',
            'RUBIT': 'RUBIT',
            'Ruble': 'RUR',
            'Rubycoin': 'RBY',
            'RUC': 'RUC',
            'RUP': 'RUP',
            'RUPX': 'RUPX',
            'RUST': 'RUST',
            'RVT': 'RVT',
            'SAFEX': 'SAFEX',
            'SAK': 'SAK',
            'SAN': 'SAN',
            'SANDG': 'SANDG',
            'SBD': 'SBD',
            'SBIT': 'SBIT',
            'SBT': 'SBT',
            'SCAN': 'SCAN',
            'SCB': 'SCB',
            'SCITW': 'SCITW',
            'SCL': 'SCL',
            'SCRPT': 'SCRPT',
            'SCRT': 'SCRT',
            'SCS': 'SCS',
            'SCT': 'SCT',
            'SDT': 'SDT',
            'SED': 'SED',
            'SEL': 'SEL',
            'SEN': 'SEN',
            'SEQ': 'SEQ',
            'SET': 'SET',
            'SEV': 'SEV',
            'Sexcoin': 'SXC',
            'SFE': 'SFE',
            'SGC': 'SGC',
            'SH': 'SH',
            'ShadowCash': 'SDC',
            'SHDW': 'SHDW',
            'SHELL': 'SHELL',
            'Shift': 'SHIFT',
            'SHREK': 'SHREK',
            'Siacoin': 'SC',
            'Siberian chervonets': 'SIB',
            'SIGT': 'SIGT',
            'SIGU': 'SIGU',
            'SIX': 'SIX',
            'SKI': 'SKI',
            'SLEEP': 'SLEEP',
            'SLFI': 'SLFI',
            'Sling': 'SLING',
            'SLS': 'SLS',
            'SMBR': 'SMBR',
            'SMC': 'SMC',
            'SmileyCoin': 'SMLY',
            'SNC': 'SNC',
            'SNG': 'SNG',
            'SNGLS': 'SNGLS',
            'SNM': 'SNM',
            'SNRG': 'SNRG',
            'SOAR': 'SOAR',
            'Solarcoin': 'SLR',
            'SOLO': 'SOLO',
            'SongCoin': 'SONG',
            'SOUL': 'SOUL',
            'SP': 'SP',
            'SPACE': 'SPACE',
            'SPC': 'SPC',
            'SPEC': 'SPEC',
            'SPEX': 'SPEX',
            'Sphere': 'SPHR',
            'SPM': 'SPM',
            'SPORT': 'SPORT',
            'SpreadCoin': 'SPR',
            'SPT': 'SPT',
            'Squall Coin': 'SQC',
            'SRND': 'SRND',
            'SSC': 'SSC',
            'SSTC': 'SSTC',
            'STA': 'STA',
            'STAR': 'STAR',
            'Startcoin': 'START',
            'Status': 'SNT',
            'STE': 'STE',
            'Stealthcoin': 'XST',
            'Steem': 'STEEM',
            'Stellar': 'STR',
            'Stellar': 'XLM',
            'Steps': 'STEPS',
            'Sterlingcoin': 'SLG',
            'STHR': 'STHR',
            'STK': 'STK',
            'STO': 'STO',
            'STONK': 'STONK',
            'STORJ': 'STORJ',
            'Storjcoin X': 'SJCX',
            'STP': 'STP',
            'STRAT': 'STRAT',
            'STRB': 'STRB',
            'Stress': 'STS',
            'STRP': 'STRP',
            'STV': 'STV',
            'STX': 'STX',
            'SUMO': 'SUMO',
            'SUPER': 'SUPER',
            'SUR': 'SUR',
            'SUS': 'SUS',
            'SVC': 'SVC',
            'SWEET': 'SWEET',
            'SWING': 'SWING',
            'SWT': 'SWT',
            'SydPak Coin': 'SDP',
            'Synereo': 'AMP',
            'SYNX': 'SYNX',
            'Syscoin': 'SYS',
            'TAA': 'TAA',
            'TAAS': 'TAAS',
            'TAJ': 'TAJ',
            'TAK': 'TAK',
            'TAKE': 'TAKE',
            'TALK': 'TALK',
            'TAM': 'TAM',
            'TAO': 'TAO',
            'TAP': 'TAP',
            'TB': 'TB',
            'TBT': 'TBT',
            'TC': 'TC',
            'TCASH': 'TCASH',
            'TCOIN': 'TCOIN',
            'TEAM': 'TEAM',
            'TECH': 'TECH',
            'TEKcoin': 'TEK',
            'TELL': 'TELL',
            'TERA': 'TERA',
            'TERI': 'TERI',
            'TERRA': 'TERRA',
            'Terracoin': 'TRC',
            'TESLA': 'TESLA',
            'TeslaCoin': 'TES',
            'TET': 'TET',
            'TFL': 'TFL',
            'THOM': 'THOM',
            'THS': 'THS',
            'Tickets': 'TIX',
            'TIDE': 'TIDE',
            'TileCoin': 'XTC',
            'TIM': 'TIM',
            'TIME': 'TIME',
            'Titcoin': 'TIT',
            'TittieCoin': 'TTC',
            'TKN': 'TKN',
            'TKR': 'TKR',
            'TKS': 'TKS',
            'TLAC': 'TLAC',
            'TLE': 'TLE',
            'TMC': 'TMC',
            'TMRW': 'TMRW',
            'TNG': 'TNG',
            'TNT': 'TNT',
            'TOA': 'TOA',
            'TODAY': 'TODAY',
            'TOKEN': 'TOKEN',
            'TOT': 'TOT',
            'TP1': 'TP1',
            'TPG': 'TPG',
            'TRA': 'TRA',
            'Transfercoin': 'TX',
            'TRAP': 'TRAP',
            'TRIG': 'TRIG',
            'TROLL': 'TROLL',
            'TRON': 'TRON',
            'TRS': 'TRS',
            'TRST': 'TRST',
            'TrumpCoin': 'TRUMP',
            'TRUST': 'TRUST',
            'TRX': 'TRX',
            'TSE': 'TSE',
            'Turron': 'TUR',
            'TWERK': 'TWERK',
            'TWO': 'TWO',
            'UAE': 'UAE',
            'Ubiquoin': 'UBIQ',
            'UBQ': 'UBQ',
            'UET': 'UET',
            'UIS': 'UIS',
            'Ukrainian Hryvnia': 'UAH',
            'UNB': 'UNB',
            'UNC': 'UNC',
            'Unfed': 'UNF',
            'UNI': 'UNI',
            'Universal Currency': 'UNIT',
            'Unobtanium': 'UNO',
            'UNRC': 'UNRC',
            'UNY': 'UNY',
            'URC': 'URC',
            'Uro': 'URO',
            'US Dollar': 'USD',
            'USC': 'USC',
            'USDE': 'USDE',
            'UTA': 'UTA',
            'UTLE': 'UTLE',
            'UXC': 'UXC',
            'VAK': 'VAK',
            'VAL': 'VAL',
            'VASH': 'VASH',
            'Vcash': 'XVC',
            'VEC': 'VEC',
            'VEC2': 'VEC2',
            'VEG': 'VEG',
            'VEN': 'VEN',
            'VENE': 'VENE',
            'VER': 'VER',
            'Verge': 'XVG',
            'VeriCoin': 'VRC',
            'Vertcoin': 'VTC',
            'Viacoin': 'VIA',
            'VIB': 'VIB',
            'VIP Tokens': 'VIP',
            'VK': 'VK',
            'VLT': 'VLT',
            'VLTC': 'VLTC',
            'VNTX': 'VNTX',
            'VOISE': 'VOISE',
            'VOL': 'VOL',
            'Voxels': 'VOX',
            'VPNCoin': 'VPN',
            'VPRC': 'VPRC',
            'VRM': 'VRM',
            'VRP': 'VRP',
            'VRS': 'VRS',
            'VSL': 'VSL',
            'VSX': 'VSX',
            'VTL': 'VTL',
            'VTR': 'VTR',
            'VTY': 'VTY',
            'VUC': 'VUC',
            'WA': 'WA',
            'WARP': 'WARP',
            'WASH': 'WASH',
            'WAV': 'WAV',
            'WAVES': 'WAVES',
            'WAY': 'WAY',
            'WCASH': 'WCASH',
            'WCN': 'WCN',
            'WEA': 'WEA',
            'WETT': 'WETT',
            'WEX': 'WEX',
            'WGO': 'WGO',
            'WGR': 'WGR',
            'Whitecoin': 'XWC',
            'WHO': 'WHO',
            'WIC': 'WIC',
            'Wild Beast Block': 'WBB',
            'WIN': 'WIN',
            'WINE': 'WINE',
            'WINGS': 'WINGS',
            'WINK': 'WINK',
            'WMC': 'WMC',
            'WMG': 'WMG',
            'Woodcoin': 'LOG',
            'WOP': 'WOP',
            'Worldcoin': 'WDC',
            'WRT': 'WRT',
            'WTHC': 'WTHC',
            'WTT': 'WTT',
            'X2': 'X2',
            'XAUR': 'XAUR',
            'Xaurum': 'XAU',
            'XAV': 'XAV',
            'XB': 'XB',
            'XBG': 'XBG',
            'XBP': 'XBP',
            'XBS': 'XBS',
            'XBTS': 'XBTS',
            'XBU': 'XBU',
            'XBY': 'XBY',
            'XCXT': 'XCXT',
            'XDE': 'XDE',
            'XDE2': 'XDE2',
            'XEL': 'XEL',
            'XET': 'XET',
            'XFC': 'XFC',
            'XFCX': 'XFCX',
            'XGB': 'XGB',
            'XGTC': 'XGTC',
            'XID': 'XID',
            'XIN': 'XIN',
            'XJO': 'XJO',
            'XLC': 'XLC',
            'XLTCG': 'XLTCG',
            'XMINE': 'XMINE',
            'XMS': 'XMS',
            'XMY': 'XMY',
            'XNC': 'XNC',
            'XNX': 'XNX',
            'XOC': 'XOC',
            'XODUS': 'XODUS',
            'XOM': 'XOM',
            'XOT': 'XOT',
            'XPC': 'XPC',
            'XPD': 'XPD',
            'XPO': 'XPO',
            'XPRO': 'XPRO',
            'XPS': 'XPS',
            'XQN': 'XQN',
            'XRC': 'XRC',
            'XRL': 'XRL',
            'XSP': 'XSP',
            'XSPEC': 'XSPEC',
            'XSSX': 'XSSX',
            'XSY': 'XSY',
            'XT': 'XT',
            'XTO': 'XTO',
            'XTP': 'XTP',
            'XTZ': 'XTZ',
            'XUP': 'XUP',
            'XVE': 'XVE',
            'XVP': 'XVP',
            'XVS': 'XVS',
            'XZA': 'XZA',
            'YAY': 'YAY',
            'YBT': 'YBT',
            'YET': 'YET',
            'YMC': 'YMC',
            'YOC': 'YOC',
            'YOVI': 'YOVI',
            'YOY': 'YOY',
            'ZayedCoin': 'ZYD',
            'ZBCN': 'ZBCN',
            'Zcash': 'ZEC',
            'Zcash classic': 'ZCL',
            'ZCC': 'ZCC',
            'Zcoin': 'XZC',
            'ZECD': 'ZECD',
            'Zeitcoin': 'ZEIT',
            'ZEN': 'ZEN',
            'ZENI': 'ZENI',
            'Zetacoin': 'ZET',
            'ZiftrCOIN': 'ZRC',
            'Zilbercoin': 'ZBC',
            'ZLQ': 'ZLQ',
            'ZMC': 'ZMC',
            'ZNE': 'ZNE',
            'ZNY': 'ZNY',
            'ZOOM': 'ZOOM',
            'ZRX': 'ZRX',
            'ZSC': 'ZSC',
            'ZUR': 'ZUR'
        }
        coins = {}

        for coin in coin_list:
            # all lower
            coins[coin.lower()] = coin_list[coin].lower()
            # all codes
            coins[coin_list[coin].lower()] = coin_list[coin].lower()
            # Duplicate coins with "coin"/"cash" in name because of natural
            # language,  bitcoin bit coin / zcash z cash
            if "coin" in coin.lower():
                coins[coin.lower().replace("coin",
                                           " coin ").rstrip().lstrip()] = \
                    coin_list[
                        coin].lower()
            if "cash" in coin.lower():
                coins[coin.lower().replace("cash",
                                           " cash ").rstrip().lstrip()] = \
                    coin_list[
                    coin].lower()
        self.coins = coins

    def stop(self):
        pass


def create_skill():
    return CryptocurrencySkill()
